### ISSUE TITLE
Malformed vfib file

### ISSUE THREAD

**Issue by RP-NL** [gabordewit/SLIDE#1]
When I try to import the virtual devices I get an error message "Malformed vfib file".

**Comment by gabordewit** [comment]
HI @RP-NL ,

Do you see this malformed file message after unzipping the file and selecting one of the individual VFIB files or when you try to upload the zipfile that you get when cloning this repository?

If you also see the message when you unzip the content of this repository and selecting either of the two virtual devices (all_slides or Single_slide) I hope you can help me with the version of the Home center you are running and the firmware of the HC on top and the steps you are taking to install the Slide virtual device.

If you see the message when trying to upload the entire zip this is more logical, the zip contains all the content you would need to run the SLIDE within Fibaro, so that includes Scenes, Images for the scenes, the virtual devices, the install instructions etc so Fibaro has no clue what to do with it.

Hope I can help you out and get it installed, I got this configuration and code running on a Home center 2 with firmware version 4.580.

**Comment by RP-NL** [comment]
Hello Gabor,

Sorry for my late reply. I tried again today and now it's just working fine
to load the VFIB files.

I hope I find some time in the weekend to get the integration done.

Thank you very much for your time and sharing your code!

Kind regards

**Comment by RP-NL** [comment]
Hello Gabor,

It has taken me a bit longer than expected but I've the basics working.
Thank you.

Have a nice weekend.

Ruud
